# Generated by Django 4.2.1 on 2023-05-07 21:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteauth', '0002_alter_websiteuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteuser',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='profile-picture'),
        ),
    ]
